export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CHECK_OUT_PRODUCTS_FROM_CART = "CHECK_OUT_PRODUCTS_FROM_CART";

export const SWITCH_CURRENCY = "SWITCH_CURRENCY";
